version: '2'
services:
  epmgateway-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/epmgateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=epmgateway
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
